### ISSUE TITLE
Incompatible with latest Salmon

### ISSUE THREAD

**Issue by bug1303** [juugii/ikura#1]
From Salmon 0.99 a new indexing structure has been introduced.
When trying to build an ikura index, it fails with :

> Exception : [Error: RapMap-based indexing is not supported in this version of salmon.]
> salmon index was invoked improperly.

I needed to install salmon 0.14.2 to solve the issue.

**Comment by bug1303** [comment]
Actually, needed to go back to salmon 0.13.1 since otherwise ikura's call of alevin resulted in:
`Exception : [unrecognised option '--dumpCsvCounts']. Exiting.` 

According to salmon v0.14.0 release notes : 
> `--dumpCsvCounts` (swapped in favor of mtx with the flag `--dumpMtx`)

**Comment by juugii** [comment]
Sorry for the late answer, I did miss notifications.
Many thanks for reporting and your time investigating the right salmon version. I edited the REAME to point users to the right salmon version.
In latest versions, salmon has somewhat merged with UMI-tools. Thus integration with Ikura will require some time that I can't invest right now. But PR are welcome.
Thanks again!
