### ISSUE TITLE
Failed to create txp2gene_*.tsv

### ISSUE THREAD

**Issue by Morgenlefay** [juugii/ikura#2]
Build index with fasta and gtf files from gencode, but failed to create txp2gene_*.tsv

**Comment by juugii** [comment]
Can you give more details on the error output ?
Is awk installed on your machine and directly callable in the CLI ?
What version of awk are you using ?

**Comment by Morgenlefay** [comment]
Awk version: 4.1.4. The awk can be directly called in the CLI.
./ikura --warmup -p 12 -t gencode.v33.transcripts.fa -a gencode.v33.annotation.gtf -i Human/hg_index
When index was built, the error was reported: 
building additional files...
./sources/warmup: line 16: Human/hg_index/txp2gene_Human/hg_index.tsv: No such file or directory

**Comment by juugii** [comment]
You should pass a _**name**_ for the index (option [-i|--index]), not a _**path**_:
`./ikura --warmup -p 8 -t gencode.v33.transcripts.fa -a gencode.v33.annotation.gtf -i hg_index
`

Expected output:
```
[2020-03-22 15:37:11.137] [jLog] [info] building index
[2020-03-22 15:37:11.138] [jointLog] [info] [Step 1 of 4] : counting k-mers
[...]
Elapsed time: 10.5928s
[2020-03-22 15:40:25.472] [jLog] [info] done building index
building additional files...
Done.
Index successfully built.
```
You can then, _optionally_, move the index folder afterwards:
```
mkdir Human
mv hg_index/ Human/
```
